# WEST
#
# keyboard: corne (https://github.com/foostan/crkbd)
# firmware: zmk (https://zmk.dev/)
# layout: hands down (https://sites.google.com/alanreiser.com/handsdown/)
#
# nugatio@2024.09.20 (https://github.com/nugatio/zmk-corne-config)

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
